// libros-webapp/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../services/auth.service';
import { TokenStorageService } from '../services/token-storage.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  form: any = {
    email: null,
    password: null
  };
  isLoggedIn = false;
  isLoginFailed = false;

  constructor(private router: Router, private authService: AuthService, private tokenStorage: TokenStorageService) { }

  ngOnInit(): void {
    if(this.tokenStorage.getToken()) {
      this.isLoggedIn = true;
    }
    if(this.isLoggedIn){
      this.router.navigate(['/']);
    }
  }

  onSubmit(): void {
    const {email, password} = this.form;

    this.authService.login(email, password).subscribe(
      data => {
        this.tokenStorage.saveToken(data.token);
        this.tokenStorage.saveUser(data);

        this.isLoginFailed = false;
        this.isLoggedIn = true;
        this.reloadPage();
      },
    );
  }

  reloadPage(): void {
    window.location.reload();
  }
}

<div *ngIf="!isLoggedIn" class="flex items-center justify-center mt-12">
    <div class="px-8 py-6 mt-4 text-left bg-white shadow-lg">
        <h3 class="text-2xl font-bold text-center">Zaloguj się do swojego konta</h3>
        <form name="form" (ngSubmit)="f.form.valid && onSubmit()" #f="ngForm" novalidate>
            <div class="mt-4">
                <div>
                    <label class="block" for="email">Email</label>
                            <input [(ngModel)]="form.email" required #username="ngModel" name="email" type="text" placeholder="Email"
                                class="form-control w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
                                <div class="alert alert-danger" role="alert" *ngIf="username.errors && f.submitted">Username is required!</div>
                </div>
                <div class="mt-4">
                    <label class="block">Hasło</label>
                            <input #password="ngModel" minlength="6" required [(ngModel)]="form.password" name="password" type="password" placeholder="Hasło"
                                class="form-control w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
                                <div class="alert alert-danger" role="alert" *ngIf="password.errors && f.submitted"> 
                                    <div *ngIf="password.errors.required">Password is required</div>
                                    <div *ngIf="password.errors.minlength">Password must be at least 6 characters</div>
                                </div>
                </div>
                <div class="flex items-baseline justify-between">
                    <button class="px-6 py-2 mt-4 text-white bg-blue-600 rounded-lg hover:bg-blue-900">Zaloguj</button>
                </div>
            </div>
            <div class="alert alert-danger" role="alert"*ngIf="f.submitted && isLoginFailed">Login failed</div>
        </form>
    </div>
</div>

// libros-webapp/src/views/Login.vue
<template>
  <div class="w-full max-w-xs">
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
        Email
      </label>
      <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Username">
    </div>
    <div class="mb-6">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
        Hasło
      </label>
      <input class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="******************">
      <p class="text-red-500 text-xs italic">Please choose a password.</p>
    </div>
    <div class="flex items-center justify-between">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button">
        Zaloguj
      </button>
      <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
        Przypomnij hasło
      </a>
    </div>
  </form>
</div>
</template>

<script>
export default {
  data() {
    return {
        loading: false,
        message: "",
      email: "",
      password: "",
    };
  },
  computed: {
      loggedIn() {
          return this.$store.state.auth.status.loggedIn;
      },
  },
  created() {
      if(this.loggedIn){
          this.$router.push("/")
      }
  },
  methods: {
    handleLogin() {
      const user = { email: this.email, password: this.password };
      this.$store.dispatch("auth/login", user).then(
        () => {
          this.$router.push("/");
        },
        (error) => {
          this.message =
            (error.response &&
              error.response.data &&
              error.response.data.message) ||
            error.message ||
            error.toString();
        }
      );
    },
  },
};
</script>

<style>
  .form {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;

  }

  .input {
    margin: 5px;
    font-size: 16px;
  }

  .btn {
    font-size: 16px;
  }
</style>
